## Упражнения по библиотеке Numpy

In [4]:
import numpy as np

In [5]:
import  scipy

In [6]:
import time

In [7]:
import os

In [8]:
import matplotlib.pyplot as plt

In [41]:
import math

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [9]:
import random


array = [random.randint(0, 10) for _ in range(15)]
print("Исходный массив:", array)


for i in range(len(array)):
    if 3 < array[i] < 8:  
        array[i] = -array[i]

print("Измененный массив:", array)

Исходный массив: [9, 1, 0, 2, 5, 0, 4, 4, 10, 6, 0, 5, 3, 2, 8]
Измененный массив: [9, 1, 0, 2, -5, 0, -4, -4, 10, -6, 0, -5, 3, 2, 8]


**2.** Заменить максимальный элемент случайного массива на 0

In [10]:
array = [random.randint(1, 20) for _ in range(15)]
print("Исходный массив:", array)


max_value = max(array)


for i in range(len(array)):
    if array[i] == max_value:
        array[i] = 0

print("Массив после замены (всех максимумов):", array)

Исходный массив: [18, 17, 2, 16, 13, 14, 6, 20, 18, 12, 17, 3, 3, 14, 14]
Массив после замены (всех максимумов): [18, 17, 2, 16, 13, 14, 6, 0, 18, 12, 17, 3, 3, 14, 14]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [11]:


arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


result = np.array(np.meshgrid(*arr)).T.reshape(-1, arr.shape[0])

print("Исходный массив:")
print(arr)
print("\nПрямое произведение:")
print(result)
print(f"\nРазмер: {result.shape}")

Исходный массив:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Прямое произведение:
[[1 4 7]
 [1 5 7]
 [1 6 7]
 [2 4 7]
 [2 5 7]
 [2 6 7]
 [3 4 7]
 [3 5 7]
 [3 6 7]
 [1 4 8]
 [1 5 8]
 [1 6 8]
 [2 4 8]
 [2 5 8]
 [2 6 8]
 [3 4 8]
 [3 5 8]
 [3 6 8]
 [1 4 9]
 [1 5 9]
 [1 6 9]
 [2 4 9]
 [2 5 9]
 [2 6 9]
 [3 4 9]
 [3 5 9]
 [3 6 9]]

Размер: (27, 3)


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [19]:

A = np.array([
    [1, 2, 3],    
    [4, 5, 6],    
    [1, 4, 2]     
])

B = np.array([[1, 2], [4, 5]])

def find_rows_at_least_one(A, B):
 
    A_sets = [set(row) for row in A]
    B_sets = [set(row) for row in B]
    
    result = []
    for i, a_set in enumerate(A_sets):
      
        satisfies_all = True
        for b_set in B_sets:
         
            if len(a_set.intersection(b_set)) == 0:
                satisfies_all = False
                break
        result.append(satisfies_all)
    
    return np.array(result)


A = np.array([
    [1, 2, 3],      
    [4, 5, 6],  
    [1, 4, 7],    
    [2, 8, 9],     
    [5, 10, 11],    
    [1, 5, 12],     
    [3, 6, 9],      
    [2, 4, 13]      
])

B = np.array([[1, 2], [4, 5]])

mask = find_rows_at_least_one(A, B)
result = A[mask]
print(result)

[[ 1  4  7]
 [ 1  5 12]
 [ 2  4 13]]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [ ]:

matrix = np.array([[1,2,3],[4,4,4],[5,5,6],[7,8,9],[2,2,2],
                   [3,3,4],[1,1,1],[6,7,8],[9,9,9],[0,1,2]])


result = matrix[np.ptp(matrix, axis=1) != 0]
print(result)

**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [ ]:

def unique_rows_float(arr, tolerance):
   
   
    arr_rounded = np.round(arr / tolerance) * tolerance
    
    return np.unique(arr_rounded, axis=0)

# Пример с числами с плавающей точкой
arr_float = np.array([
    [1.0, 2.0, 3.0],
    [1.000000001, 2.000000001, 3.000000001],  # почти дубликат
    [4.0, 5.0, 6.0],
    [1.0, 2.0, 3.0],  # точный дубликат
])

unique_float = unique_rows_float(arr_float, tolerance=1e-6)
print("\nМассив float без дубликатов (с учетом допуска):")
print(unique_float)

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [25]:
X = np.array([[1, 0, 1],
              [2, 0, 2],
              [3, 0, 3],
              [4, 4, 4]])

# Решение в одну строку
result = np.prod(np.diag(X)[np.diag(X) != 0])
print(f"Произведение ненулевых элементов на диагонали: {result}")  

Произведение ненулевых элементов на диагонали: 3


Реализация без numpay

In [28]:
def diagonal_nonzero_product(matrix):
    
    
    rows = len(matrix)
    cols = len(matrix[0])
    

    diagonal_length = min(rows, cols)
    
    product = 1
    
    for i in range(diagonal_length):
        element = matrix[i][i]
        if element != 0:
            product *= element
           
    return product 

result = diagonal_nonzero_product(X)

print(f"Произведение ненулевых элементов на диагонали: {result}") 

Произведение ненулевых элементов на диагонали: 3


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [ ]:
x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2]) 
same_multiset_one_line = lambda x, y: np.array_equal(np.sort(x), np.sort(y))
print(f"\nsame_multiset_one_line(x, y) = {same_multiset_one_line(x, y)}")

реализация без numpy

In [29]:
def are_multisets_equal_1(x, y):
   
    return sorted(x) == sorted(y)


x = [1, 2, 2, 4]
y = [4, 2, 1, 2]
print(are_multisets_equal_1(x, y))  

True


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [ ]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])

# Решение в одну строку
result = np.max(x[1:][x[:-1] == 0]) if np.any(x[:-1] == 0) else None

print(f"Максимальный элемент после нуля: {result}")  

In [ ]:
реализация без numpy

In [36]:
def max_after_zero_1(x):
    max_val = None
    for i in range(1, len(x)):
        if x[i-1] == 0:
            if max_val is None or x[i] > max_val:
                max_val = x[i]
    
    return max_val

x = [6, 2, 0, 3, 0, 0, 5, 7, 0]
print(max_after_zero_1(x))  # 5

5


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [38]:

def rle_oneline(x):
   
    return (lambda p: (x[p], np.diff(np.append(p, len(x)))))(np.where(np.diff(x, prepend=x[0]-1))[0]) if len(x) > 0 else (np.array([]), np.array([]))

x = np.array([2, 2, 2, 3, 3, 3, 5])
print(f"Одна строка: {rle_oneline(x)}")


Одна строка: (array([2, 3, 5]), array([3, 3, 1], dtype=int64))


In [ ]:
реализация без numpy

In [37]:
def rle_encode_1(x):
    if not x:
        return [], []
    
    values = []
    counts = []
    
    current_value = x[0]
    current_count = 1
    
    for i in range(1, len(x)):
        if x[i] == current_value:
            current_count += 1
        else:
            values.append(current_value)
            counts.append(current_count)
            current_value = x[i]
            current_count = 1
    
    values.append(current_value)
    counts.append(current_count)
    
    return values, counts


x = [2, 2, 2, 3, 3, 3, 5]
values, counts = rle_encode_1(x)
print("Значения:", values)  
print("Счетчики:", counts)  

Значения: [2, 3, 5]
Счетчики: [3, 3, 1]


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [ ]:
реализация без numpy

In [39]:
def euclidean_distance_naive(X, Y): 
    n = len(X)
    m = len(Y)
    d = len(X[0])
       
    dist_matrix = [[0.0 for _ in range(m)] for _ in range(n)]
    
    for i in range(n):
        for j in range(m):
            sum_squared = 0.0
            for k in range(d):
                diff = X[i][k] - Y[j][k]
                sum_squared += diff * diff
            
            dist_matrix[i][j] = math.sqrt(sum_squared)
    
    return dist_matrix

In [42]:
X = np.array([[1, 2], [3, 4]])
Y = np.array([[5, 6], [7, 8]])
dist_matrix = euclidean_distance_naive(X,Y)
print("Матрица расстояний:")
print(dist_matrix)

Матрица расстояний:
[[5.656854249492381, 8.48528137423857], [2.8284271247461903, 5.656854249492381]]


In [ ]:
from scipy.spatial.distance import cdist

def euclidean_dist_cdist(X, Y):

    return cdist(X, Y, metric='euclidean')

# Использование
X = np.array([[1, 2], [3, 4]])
Y = np.array([[5, 6], [7, 8]])


dist_matrix = euclidean_dist_cdist(X, Y)


print("Матрица расстояний:")
print(dist_matrix)

X = np.random.rand(500, 10)
Y = np.random.rand(300, 10)

start = time.time()
dist1 = my_cdist(X, Y)
t1 = time.time() - start

print(f"Время выполнения: {t1:.4f} сек")


In [ ]:
def my_cdist(X, Y):
    
    X_sq = np.sum(X**2, axis=1)[:, np.newaxis]
    Y_sq = np.sum(Y**2, axis=1)[np.newaxis, :]
    XY = X @ Y.T
     
    dist_sq = X_sq + Y_sq - 2 * XY
    dist_sq = np.maximum(dist_sq, 0)  # исправляем ошибки округления
    return np.sqrt(dist_sq)

X = np.random.rand(500, 10)
Y = np.random.rand(300, 10)

start = time.time()
dist1 = my_cdist(X, Y)
t1 = time.time() - start

print(f"Время выполнения: {t1:.4f} сек")



Вывод: для небольших данных разница не существенна

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [ ]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [ ]:
calorie_stats = np.loadtxt(
   "cereal.csv",
    delimiter=","

)


In [ ]:
print("exists:", os.path.exists("cereal.csv"))
print("size:", os.path.getsize("cereal.csv"))

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [ ]:

crunchie_calories = 60


average_competitor_calories = np.mean(calorie_stats)


average_calories = average_competitor_calories - crunchie_calories


print(average_calories)

3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [ ]:
calorie_stats_sorted = np.sort(calorie_stats)


print(calorie_stats_sorted)

In [ ]:
# Построение гистограммы распределения калорий
plt.figure()
plt.hist(calorie_stats, bins=10)
plt.xlabel("Calories")
plt.ylabel("Frequency")
plt.title("Distribution of Calories")

plt.show()

4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [ ]:
# Медиана набора данных
median_calories = np.median(calorie_stats)

# Среднее значение (для сравнения)
mean_calories = np.mean(calorie_stats)


print("Median calories:", median_calories)
print("Mean calories:", mean_calories)

5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [ ]:
target = 60

for p in range(101):
    value = np.percentile(calorie_stats, p)
    if value > target:
        percentile_number = p
        nth_percentile = value
        break

print("Percentile number:", percentile_number)
print("Percentile value:", nth_percentile)

In [ ]:
plt.figure()
plt.hist(calorie_stats, bins=10)
plt.axvline(60)
plt.axvline(nth_percentile)

plt.xlabel("Calories")
plt.ylabel("Frequency")
plt.title("Calories Distribution with Percentile Threshold")

plt.show()

6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [ ]:

more_calories = np.sum(calorie_stats > 60) / len(calorie_stats) * 100

print(more_calories)

7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [ ]:
calorie_std = np.std(calorie_stats)

print(calorie_std)

In [ ]:
plt.figure()
plt.hist(calorie_stats, bins=10)

# Линии среднего и стандартного отклонения
plt.axvline(mean_calories)
plt.axvline(mean_calories + calorie_std)
plt.axvline(mean_calories - calorie_std)

# Линия для CrunchieMunchies (60 калорий)
plt.axvline(60)

plt.xlabel("Calories")
plt.ylabel("Frequency")
plt.title("Calories Distribution with Mean and Standard Deviation")

plt.show()

8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

На основе анализа данных видно, что средняя калорийность хлопьев на рынке превышает 60 калорий на порцию, а также что более половины продуктов содержат калорийность выше этого значения. Медиана и стандартное отклонение показывают, что распределение калорий достаточно широкое, то есть на рынке представлены как низкокалорийные, так и более калорийные варианты. На этом фоне CrunchieMunchies с 60 калориями выглядят более лёгким и сбалансированным продуктом. Эти данные Mycrunch может использовать в маркетинге, позиционируя CrunchieMunchies как более здоровую альтернативу большинству конкурентов, делая акцент на контроле калорийности и подходящем выборе для потребителей, следящих за питанием.